#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OrderBook.Resource", IsApplication=true)]

namespace OrderBook
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Syncfusion.Data.Resource.String.library_name = global::OrderBook.Resource.String.library_name;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Ascending = global::OrderBook.Resource.Drawable.Ascending;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Descending = global::OrderBook.Resource.Drawable.Descending;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Drag_and_Drop_Icon = global::OrderBook.Resource.Drawable.Drag_and_Drop_Icon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.DragDown = global::OrderBook.Resource.Drawable.DragDown;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.DragUp = global::OrderBook.Resource.Drawable.DragUp;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.error2 = global::OrderBook.Resource.Drawable.error2;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.FirstPageIcon = global::OrderBook.Resource.Drawable.FirstPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.GroupCollapse = global::OrderBook.Resource.Drawable.GroupCollapse;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.GroupExpander = global::OrderBook.Resource.Drawable.GroupExpander;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.GroupIcon_Android = global::OrderBook.Resource.Drawable.GroupIcon_Android;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.LastPageIcon = global::OrderBook.Resource.Drawable.LastPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.NextPageIcon = global::OrderBook.Resource.Drawable.NextPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.PrevPageIcon = global::OrderBook.Resource.Drawable.PrevPageIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.ResizingIcon = global::OrderBook.Resource.Drawable.ResizingIcon;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.Sort = global::OrderBook.Resource.Drawable.Sort;
			global::Syncfusion.SfDataGrid.Android.Resource.Drawable.SortDescending = global::OrderBook.Resource.Drawable.SortDescending;
			global::Syncfusion.SfDataGrid.Android.Resource.Layout.ScrollViewer = global::OrderBook.Resource.Layout.ScrollViewer;
			global::Syncfusion.SfDataGrid.Android.Resource.String.library_name = global::OrderBook.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Ascending = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Descending = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Drag_and_Drop_Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int DragDown = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int DragUp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int error2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int FirstPageIcon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int GroupCollapse = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int GroupExpander = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int GroupIcon_Android = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int LastPageIcon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int NextPageIcon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int PrevPageIcon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ResizingIcon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Sort = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int SortDescending = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int Relative = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ScrollViewer = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
